In [2]:
from statsbombpy import sb
competitions = sb.competitions()
import pandas as pd




matches = sb.matches(competition_id= 55, season_id=282)
print(matches.shape)
matches.head()
print(matches.columns.tolist())

spain_matches = matches[(matches['home_team'] == 'Spain') | (matches['away_team'] == 'Spain')]
print(spain_matches[['match_id', 'match_date', 'home_team', 'away_team', 'home_score', 'away_score', 'competition_stage']])

game1 = sb.events(match_id= 3930160)
print(game1["type"].value_counts())

lineup= game1[ (game1['type'] == 'Starting XI')]
print (lineup)
print(lineup.columns.tolist())

print(lineup['tactics'].iloc[0])
players_list = lineup['tactics'].iloc[0]['lineup']

spain_lineup = []

for p in players_list:
    spain_lineup.append({
    "player": p['player']['name'],
    "position": p['position']["name"],
    "jersey_number": p['jersey_number']
    })

print(spain_lineup)

print(pd.DataFrame(spain_lineup))

C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

(51, 22)
['match_id', 'match_date', 'kick_off', 'competition', 'season', 'home_team', 'away_team', 'home_score', 'away_score', 'match_status', 'match_status_360', 'last_updated', 'last_updated_360', 'match_week', 'competition_stage', 'stadium', 'referee', 'home_managers', 'away_managers', 'data_version', 'shot_fidelity_version', 'xy_fidelity_version']
    match_id  match_date home_team away_team  home_score  away_score  \
1    3943043  2024-07-14     Spain   England           2           1
2    3942752  2024-07-09     Spain    France           2           1
8    3942226  2024-07-05     Spain   Germany           2           1
15   3941018  2024-06-30     Spain   Georgia           4           1
18   3930179  2024-06-24   Albania     Spain           0           1
23   3930172  2024-06-20     Spain     Italy           1           0
48   3930160  2024-06-15     Spain   Croatia           3           0

   competition_stage
1              Final
2        Semi-finals
8     Quarter-finals
15       Round of 16
18       Group Stage
23       Group Stage
48       Group Stage
type
Pass                 1048
Ball Receipt*        1016
Carry                 844
Pressure              430
Ball Recovery          75
Duel                   63
Block                  47
Goal Keeper            36
Foul Committed         29
Shot                   27
Foul Won               27
Dribble                22
Dispossessed           22
Miscontrol             18
Clearance              15
Dribbled Past          15
Interception           14
Substitution            9
Injury Stoppage         8
50/50                   8
Referee Ball-Drop       6
Half End                4
Half Start              4
Tactical Shift          3
Starting XI             2
Player Off              1
Player On               1
Shield                  1
Offside                 1
Name: count, dtype: int64
  50_50 ball_receipt_outcome ball_recovery_recovery_failure block_deflection  \
0   NaN                  NaN                            NaN              NaN
1   NaN                  NaN                            NaN              NaN

  block_offensive carry_end_location clearance_aerial_won clearance_body_part  \
0             NaN                NaN                  NaN                 NaN
1             NaN                NaN                  NaN                 NaN

  clearance_head clearance_left_foot  ... substitution_outcome  \
0            NaN                 NaN  ...                  NaN
1            NaN                 NaN  ...                  NaN

  substitution_outcome_id substitution_replacement  \
0                     NaN                      NaN
1                     NaN                      NaN

  substitution_replacement_id  \
0                         NaN
1                         NaN

                                             tactics     team team_id  \
0  {'formation': 4231, 'lineup': [{'player': {'id...    Spain     772
1  {'formation': 433, 'lineup': [{'player': {'id'...  Croatia     785

      timestamp         type under_pressure
0  00:00:00.000  Starting XI            NaN
1  00:00:00.000  Starting XI            NaN

[2 rows x 98 columns]
['50_50', 'ball_receipt_outcome', 'ball_recovery_recovery_failure', 'block_deflection', 'block_offensive', 'carry_end_location', 'clearance_aerial_won', 'clearance_body_part', 'clearance_head', 'clearance_left_foot', 'clearance_right_foot', 'counterpress', 'dribble_no_touch', 'dribble_nutmeg', 'dribble_outcome', 'duel_outcome', 'duel_type', 'duration', 'foul_committed_advantage', 'foul_committed_card', 'foul_committed_offensive', 'foul_committed_penalty', 'foul_committed_type', 'foul_won_advantage', 'foul_won_defensive', 'foul_won_penalty', 'goalkeeper_body_part', 'goalkeeper_end_location', 'goalkeeper_outcome', 'goalkeeper_position', 'goalkeeper_shot_saved_off_target', 'goalkeeper_technique', 'goalkeeper_type', 'id', 'index', 'injury_stoppage_in_chain', 'interception_outcome', 'location', 'match_id', 'minute', 'miscontrol_aerial_won', 'off_camera', 'out', 'pass_aerial_won', 'pass_angle', 'pass_assisted_shot_id', 'pass_body_part', 'pass_cross', 'pass_cut_back', 'pass_deflected', 'pass_end_location', 'pass_goal_assist', 'pass_height', 'pass_inswinging', 'pass_length', 'pass_outcome', 'pass_outswinging', 'pass_recipient', 'pass_recipient_id', 'pass_shot_assist', 'pass_switch', 'pass_technique', 'pass_through_ball', 'pass_type', 'period', 'play_pattern', 'player', 'player_id', 'position', 'possession', 'possession_team', 'possession_team_id', 'related_events', 'second', 'shot_aerial_won', 'shot_body_part', 'shot_deflected', 'shot_end_location', 'shot_first_time', 'shot_freeze_frame', 'shot_key_pass_id', 'shot_one_on_one', 'shot_outcome', 'shot_redirect', 'shot_saved_off_target', 'shot_statsbomb_xg', 'shot_technique', 'shot_type', 'substitution_outcome', 'substitution_outcome_id', 'substitution_replacement', 'substitution_replacement_id', 'tactics', 'team', 'team_id', 'timestamp', 'type', 'under_pressure']
{'formation': 4231, 'lineup': [{'player': {'id': 11748, 'name': 'Unai Simón Mendibil'}, 'position': {'id': 1, 'name': 'Goalkeeper'}, 'jersey_number': 23}, {'player': {'id': 5721, 'name': 'Daniel Carvajal Ramos'}, 'position': {'id': 2, 'name': 'Right Back'}, 'jersey_number': 2}, {'player': {'id': 22128, 'name': 'Robin Aime Robert Le Normand'}, 'position': {'id': 3, 'name': 'Right Center Back'}, 'jersey_number': 3}, {'player': {'id': 5202, 'name': 'José Ignacio Fernández Iglesias'}, 'position': {'id': 5, 'name': 'Left Center Back'}, 'jersey_number': 4}, {'player': {'id': 17620, 'name': 'Marc Cucurella Saseta'}, 'position': {'id': 6, 'name': 'Left Back'}, 'jersey_number': 24}, {'player': {'id': 6765, 'name': 'Rodrigo Hernández Cascante'}, 'position': {'id': 9, 'name': 'Right Defensive Midfield'}, 'jersey_number': 16}, {'player': {'id': 6655, 'name': 'Fabián Ruiz Peña'}, 'position': {'id': 11, 'name': 'Left Defensive Midfield'}, 'jersey_number': 8}, {'player': {'id': 316046, 'name': 'Lamine Yamal Nasraoui Ebana'}, 'position': {'id': 17, 'name': 'Right Wing'}, 'jersey_number': 19}, {'player': {'id': 30486, 'name': 'Pedro González López'}, 'position': {'id': 19, 'name': 'Center Attacking Midfield'}, 'jersey_number': 20}, {'player': {'id': 68574, 'name': 'Nicholas Williams Arthuer'}, 'position': {'id': 21, 'name': 'Left Wing'}, 'jersey_number': 17}, {'player': {'id': 3477, 'name': 'Álvaro Borja Morata Martín'}, 'position': {'id': 23, 'name': 'Center Forward'}, 'jersey_number': 7}]}
[{'player': 'Unai Simón Mendibil', 'position': 'Goalkeeper', 'jersey_number': 23}, {'player': 'Daniel Carvajal Ramos', 'position': 'Right Back', 'jersey_number': 2}, {'player': 'Robin Aime Robert Le Normand', 'position': 'Right Center Back', 'jersey_number': 3}, {'player': 'José Ignacio Fernández Iglesias', 'position': 'Left Center Back', 'jersey_number': 4}, {'player': 'Marc Cucurella Saseta', 'position': 'Left Back', 'jersey_number': 24}, {'player': 'Rodrigo Hernández Cascante', 'position': 'Right Defensive Midfield', 'jersey_number': 16}, {'player': 'Fabián Ruiz Peña', 'position': 'Left Defensive Midfield', 'jersey_number': 8}, {'player': 'Lamine Yamal Nasraoui Ebana', 'position': 'Right Wing', 'jersey_number': 19}, {'player': 'Pedro González López', 'position': 'Center Attacking Midfield', 'jersey_number': 20}, {'player': 'Nicholas Williams Arthuer', 'position': 'Left Wing', 'jersey_number': 17}, {'player': 'Álvaro Borja Morata Martín', 'position': 'Center Forward', 'jersey_number': 7}]
                             player                   position  jersey_number
0               Unai Simón Mendibil                 Goalkeeper             23
1             Daniel Carvajal Ramos                 Right Back              2
2      Robin Aime Robert Le Normand          Right Center Back              3
3   José Ignacio Fernández Iglesias           Left Center Back              4
4             Marc Cucurella Saseta                  Left Back             24
5        Rodrigo Hernández Cascante   Right Defensive Midfield             16
6                  Fabián Ruiz Peña    Left Defensive Midfield              8
7       Lamine Yamal Nasraoui Ebana                 Right Wing             19
8              Pedro González López  Center Attacking Midfield             20
9         Nicholas Williams Arthuer                  Left Wing             17
10       Álvaro Borja Morata Martín             Center Forward              7

In [17]:
xG= game1[ (game1['type'] == 'Shot')]


spain_shots = xG[(xG['team'] == 'Spain')]

spain_shots[['player', 'team', 'minute', 'location', 'shot_outcome', 'shot_body_part', 'shot_technique', 'shot_type', 'shot_statsbomb_xg']]

,player,team,minute,location,shot_outcome,shot_body_part,shot_technique,shot_type,shot_statsbomb_xg
3727,Álvaro Borja Morata Martín,Spain,6,"[98.8, 47.5]",Saved,Left Foot,Half Volley,Open Play,0.053676
3728,Lamine Yamal Nasraoui Ebana,Spain,14,"[106.5, 49.9]",Saved Off Target,Left Foot,Normal,Open Play,0.048078
3730,Álvaro Borja Morata Martín,Spain,28,"[104.1, 39.9]",Goal,Left Foot,Normal,Open Play,0.425340
3732,Fabián Ruiz Peña,Spain,31,"[103.9, 38.7]",Goal,Left Foot,Normal,Open Play,0.056130
3735,Robin Aime Robert Le Normand,Spain,35,"[114.2, 35.6]",Blocked,Head,Normal,Open Play,0.108392
3739,Daniel Carvajal Ramos,Spain,46,"[112.7, 42.4]",Goal,Right Foot,Volley,Open Play,0.301003
3741,Lamine Yamal Nasraoui Ebana,Spain,51,"[108.6, 48.3]",Saved,Left Foot,Normal,Open Play,0.281681
3742,Álvaro Borja Morata Martín,Spain,53,"[117.4, 34.5]",Wayward,Other,Normal,Open Play,0.210361
3747,Lamine Yamal Nasraoui Ebana,Spain,57,"[91.3, 45.4]",Blocked,Left Foot,Normal,Free Kick,0.042339
3748,Daniel Olmo Carvajal,Spain,73,"[93.9, 39.0]",Blocked,Right Foot,Normal,Open Play,0.027441
3752,Ferrán Torres García,Spain,87,"[109.6, 57.8]",Blocked,Right Foot,Normal,Open Play,0.012741

In [39]:
expected_goals = 'shot_statsbomb_xg'
x = sum(spain_shots[expected_goals])
print(f"Total expected goals for Spain: {x}")

Total expected goals for Spain: 2.48209888

In [40]:
checkgoal = spain_shots[spain_shots['shot_outcome'] == 'Goal']
print(checkgoal[['player', 'shot_statsbomb_xg', "shot_outcome"]])

Empty DataFrame
Columns: [player, shot_statsbomb_xg, shot_outcome]
Index: []

In [41]:
xG= game1[ (game1['type'] == 'Shot')]


croatia_shots = xG[(xG['team'] == 'Croatia')]

croatia_shots[['player', 'team', 'minute', 'location', 'shot_outcome', 'shot_body_part', 'shot_technique', 'shot_type', 'shot_statsbomb_xg']]

,player,team,minute,location,shot_outcome,shot_body_part,shot_technique,shot_type,shot_statsbomb_xg
3729,Ante Budimir,Croatia,21,"[107.7, 39.3]",Off T,Head,Normal,Open Play,0.048898
3731,Mateo Kovačić,Croatia,29,"[102.8, 38.7]",Saved,Left Foot,Normal,Open Play,0.063781
3733,Marcelo Brozović,Croatia,32,"[101.8, 40.2]",Saved,Right Foot,Normal,Open Play,0.077752
3734,Lovro Majer,Croatia,32,"[116.5, 50.1]",Off T,Right Foot,Normal,Open Play,0.106451
3736,Joško Gvardiol,Croatia,40,"[114.0, 27.5]",Off T,Left Foot,Half Volley,Open Play,0.050448
3737,Andrej Kramarić,Croatia,44,"[86.3, 47.4]",Off T,Right Foot,Normal,Open Play,0.013198
3738,Mateo Kovačić,Croatia,45,"[91.0, 30.4]",Off T,Right Foot,Normal,Open Play,0.019094
3740,Joško Gvardiol,Croatia,50,"[101.2, 24.0]",Blocked,Left Foot,Half Volley,Open Play,0.018449
3743,Josip Stanišić,Croatia,54,"[111.9, 47.8]",Blocked,Right Foot,Normal,Open Play,0.222950
3744,Ante Budimir,Croatia,54,"[117.0, 37.0]",Blocked,Head,Normal,Open Play,0.206007
3745,Andrej Kramarić,Croatia,54,"[118.4, 40.0]",Saved,Head,Normal,Open Play,0.710373
3746,Mateo Kovačić,Croatia,54,"[115.1, 34.4]",Wayward,Head,Normal,Open Play,0.099854
3749,Bruno Petković,Croatia,79,"[108.0, 40.0]",Saved,Right Foot,Normal,Penalty,0.783500
3750,Ivan Perišić,Croatia,83,"[101.4, 28.7]",Blocked,Right Foot,Normal,Open Play,0.035310
3751,Ivan Perišić,Croatia,83,"[87.3, 24.7]",Saved,Left Foot,Normal,Open Play,0.006943
3753,Ivan Perišić,Croatia,91,"[107.8, 27.5]",Off T,Head,Normal,Open Play,0.019090

In [42]:
expected_goals = 'shot_statsbomb_xg'
x = sum(croatia_shots[expected_goals])
print(f"Total expected goals for Croatia: {x}")

Total expected goals for Croatia: 2.48209888

In [ ]:
checkgoal = croatia_shots[croatia_shots['shot_outcome'] == 'Goal']
print(checkgoal[['player', 'shot_statsbomb_xg', "shot_outcome"]])

                player  shot_statsbomb_xg shot_outcome
3729      Ante Budimir           0.048898        Off T
3731     Mateo Kovačić           0.063781        Saved
3733  Marcelo Brozović           0.077752        Saved
3734       Lovro Majer           0.106451        Off T
3736    Joško Gvardiol           0.050448        Off T
3737   Andrej Kramarić           0.013198        Off T
3738     Mateo Kovačić           0.019094        Off T
3740    Joško Gvardiol           0.018449      Blocked
3743    Josip Stanišić           0.222950      Blocked
3744      Ante Budimir           0.206007      Blocked
3745   Andrej Kramarić           0.710373        Saved
3746     Mateo Kovačić           0.099854      Wayward
3749    Bruno Petković           0.783500        Saved
3750      Ivan Perišić           0.035310      Blocked
3751      Ivan Perišić           0.006943        Saved
3753      Ivan Perišić           0.019090        Off T

In [ ]:
print(game1['possession_team'].value_counts())

possession_team
Croatia    2015
Spain      1781
Name: count, dtype: int64

In [ ]:
counts = game1['possession_team'].value_counts()
print(counts['Spain'])
print(counts['Croatia'])

total_possesion = counts['Croatia'] + counts['Spain']
spain_possesion = counts['Spain'] / total_possesion * 100
croatia_possesion = counts['Croatia'] / total_possesion * 100
print (f"Spain possesion is : {spain_possesion:.2f}%")
print (f"Croatia Possesion: {croatia_possesion:.2f}%")

1781
2015
Spain possesion is : 46.92%
Croatia Possesion: 53.08%